version: "3"
services:
  database:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
    restart: always
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - "7000:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    restart: always
  backend:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - "8080:80"
    volumes: ["./src/api/:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    restart: always
volumes:
  db_data:
